### ISSUE TITLE
v0.4.0 Support 

### ISSUE THREAD

**Issue by EHylands** [EHylands/homebridge-anthemreceiver#2]
Please report receiver model and success using plugin. For error, please provide Homebridge log file when running ing Debug mode.

**Comment by b3ll** [comment]
Don't really have any issues to report, works beautifully with my 740.

Just wanted to say thanks for making this project!! :D

**Comment by EHylands** [comment]
Thank you for your kind words ! Please don't hesitate for any feature request !
